//
//  LSIFirstResponder.m
//  Quakes-Objc
//
//  Created by Nick Nguyen on 4/15/20.
//  Copyright © 2020 Lambda, Inc. All rights reserved.
//

#import "LSIFirstResponder.h"
@implementation LSIFirstResponder
- (instancetype)initWithName:(NSString *)name usingAge:(int)age {
    self = [super init];
    if (self) {
        // NSMutableString -> NSString (constant)
        _name = [name copy]; // protects from NSMutableString being stored
        _age = age;
    }
    return self;
}
// 3. create the instance variable
// Tell the compiler we do want the autogenerated variable
// @synthesize nameOfProperty = _nameOfInstanceVariable
@synthesize name = _name;
// 1. Setter
- (void)setName:(NSString *)name {
    // willSet
    _name = [name copy];
    // didSet
    //    [self updateViews];
}
// 2. Getter
- (NSString *)name {
    return _name;
}
@end
